[package]
name = "rnrm"
version = "0.1.8"
description = "A NPM registry manager"
edition = "2021"
license = "MIT OR Apache-2.0"
include = ["/src", "/config.ini"]

[dependencies]
clap = { version = "3.1.12", features = ["derive"] }
rust-ini = "0.18"
colored = "2"
open = "2"
