[package]
name = "rnrm"
version = "0.1.0"
description = "A NPM registry manager"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
clap = { version = "3.1.12", features = ["derive"] }
rust-ini = "0.18"
